version: '3.3'

services:
#  laracom-demo-cli:
#    build: ./demo-cli
#    environment:
#      MICRO_REGISTRY: "mdns"
#
#  laracom-demo-service:
#    build: ./demo-service
#    ports:
#      - 9091:9091
#    environment:
#      MICRO_SERVER_ADDRESS: ":9091"
#      MICRO_REGISTRY: "mdns"
#    # docker network create microservice

  laracom-user-db:
    image: mysql:5.7
    container_name: laracom-user-db
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "laracom_user"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - microservice

  laracom-nats:
    image: nats:latest
    ports:
      - 4222:4222
    restart: always
    networks:
      - microservice

  laracom-user-service:
    depends_on:
      - laracom-user-db
      - laracom-nats
    restart: on-failure
    build: ./user-service
    ports:
      - 9092:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "mdns"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "laracom-nats:4222"
      DB_HOST: "laracom-user-db:3306"
      DB_NAME: "laracom_user"
      DB_USER: "test"
      DB_PASSWORD: "test"
    networks:
      - microservice


  laracom-user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"
    networks:
      - microservice





  laracom-product-service:
    depends_on:
      - laracom-product-db
    build: ./product-service
    restart: on-failure
    ports:
      - 9093:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "laracom-product-db:3306"
      DB_NAME: "laracom_product"
      DB_USER: "product"
      DB_PASSWORD: "test"
    networks:
      - microservice

  laracom-product-cli:
    build: ./product-cli
    environment:
      MICRO_REGISTRY: "mdns"
    networks:
      - microservice

  laracom-product-db:
    image: mysql:5.7
    ports:
      - 3308:3306
    volumes:
      - db_product_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: "product"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "laracom_product"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - microservice

  laracom-micro-api:
    image: micro/micro:latest
    container_name: laracom-micro-api
    environment:
      MICRO_REGISTRY: "mdns"
    links:
      - laracom-user-service
      - laracom-product-service
    ports:
      - 8080:8080
    networks:
      - microservice
    command: service api --handler=rpc --namespace=laracom.service




volumes:
  db_data: {}
  db_product_data: {}

networks:
  microservice:
    external: true
